### PR TITLE
New Version

### PR DESCRIPTION
**Pull request by rayrw**
I have updated the website based on the new design.
Please review it.
Thanks!

### CODE REVIEW

**Comment by chpapa** [comment]
Thanks @rayrw ! @frank-oursky see if you need any revision? If you're happy with it I will merge it.

**Comment by chpapa** [comment]
@rayrw Can you use something like https://tinypng.com/ to reduce the size of these large png images?

* img/work-environment-bg.png
* img/team.jpg
* img/learn-more-bg.png
* img/4cats-eng.png
* img/bg-3.jpg

**Comment by rayrw** [comment]
@chpapa OK. Commit 5b99ee6 should do this.

**Comment by chpapa** [comment]
Thanks! Just a reminder, beware your commit changed the file's permission too :)

**Pull request merged**
